"""CLAUDIA — master conversational controller for the Vantyx dashboard.

Uses Claude (opus-4-7) with tool use to orchestrate the marketing, pricing,
and surveillance agents based on natural-language requests from Sam.
"""
from __future__ import annotations

import os

import anthropic

from .storage import (
    clear_messages,
    init_db,
    load_history_for_ui,
    load_messages,
    save_message,
)
from .tools import TOOLS, execute_tool

SYSTEM_PROMPT = """You are CLAUDIA — the master AI controller for Sam's Vantyx Pty Ltd operations dashboard.

Vantyx Pty Ltd (ABN 84 544 119 830) is an Australian International Commodity Trader and
Importer/Exporter of agricultural fertiliser products. Based Melbourne. Contact: sam@vantyx.com.au.

You orchestrate three specialised agents through tool calls:

1. **Marketing Agent** — Drafts/schedules posts (Facebook, Instagram, Twitter, LinkedIn), launches
   multi-channel campaigns, captures and forwards leads, learns from engagement metrics.

2. **Pricing Agent** — Monitors fertiliser commodity prices (Urea, DAP, MAP, MOP, Phosphate Rock,
   Ammonia, etc.) from IndexMundi and FRED. Detects significant moves, generates alerts, runs
   market analysis for buying opportunities and risks.

3. **Surveillance Agent** — Monitors market news via Google News RSS, classifies relevance and
   sentiment with Claude, generates intelligence briefings with opportunities, threats, action items.

## Operating principles

- ALWAYS use tools to fetch real data — never guess prices, post counts, or news content
- When Sam tells you to do something (draft a post, run a scan, refresh prices), use the tool immediately
- For complex requests, plan tool calls — fetch data first, then act on it
- After tools return, summarise the result cleanly with markdown (bold key numbers, use tables/lists)
- If a tool fails, explain what went wrong and suggest an alternative
- Be concise. Sam is busy. 100-300 words is usually right.

## When to act vs ask

- Clear instruction ("draft a LinkedIn post about urea") → act immediately
- Ambiguous request ("get me some leads") → ask one clarifying question
- Risky/large action (campaign budget > $1000, mass posting) → confirm before executing

## Format

Use markdown. Bold key numbers. Tables for data. Bullet lists for steps.
End with a clear status or suggested next step when applicable.
"""

_MAX_TOOL_ITERATIONS = 8
_HISTORY_LIMIT = 30


class ClaudiaAgent:

    def __init__(self) -> None:
        init_db()
        self._client: anthropic.Anthropic | None = None

    def _claude(self) -> anthropic.Anthropic:
        if self._client is None:
            self._client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
        return self._client

    def chat(self, user_text: str) -> list[dict]:
        """Send a user message, return list of UI events generated by the turn.

        UI events are dicts with `type` in:
          - "assistant": {text}        — assistant text block
          - "tool_call": {name, args}  — tool invocation
          - "tool_result": {name, preview} — tool output preview
        """
        user_text = user_text.strip()
        if not user_text:
            return []

        save_message("user", user_text)
        conversation = load_messages(limit=_HISTORY_LIMIT)

        ui_events: list[dict] = []

        for _ in range(_MAX_TOOL_ITERATIONS):
            response = self._claude().messages.create(
                model="claude-opus-4-7",
                max_tokens=4096,
                thinking={"type": "adaptive"},
                system=SYSTEM_PROMPT,
                tools=TOOLS,
                messages=conversation,
            )

            assistant_blocks = []
            tool_uses = []
            for block in response.content:
                btype = getattr(block, "type", None)
                if btype == "text":
                    text = block.text
                    if text.strip():
                        ui_events.append({"type": "assistant", "text": text})
                    assistant_blocks.append({"type": "text", "text": text})
                elif btype == "tool_use":
                    args = dict(block.input) if block.input else {}
                    ui_events.append({"type": "tool_call", "name": block.name, "args": args})
                    assistant_blocks.append({
                        "type": "tool_use",
                        "id": block.id,
                        "name": block.name,
                        "input": args,
                    })
                    tool_uses.append(block)
                elif btype == "thinking":
                    # Only preserve if signature is non-empty (omitted display gives empty sig)
                    sig = getattr(block, "signature", "") or ""
                    if sig:
                        assistant_blocks.append({
                            "type": "thinking",
                            "thinking": getattr(block, "thinking", "") or "",
                            "signature": sig,
                        })
                elif btype == "redacted_thinking":
                    # Opus 4.7 default: returns redacted_thinking blocks instead of thinking
                    data = getattr(block, "data", "") or ""
                    if data:
                        assistant_blocks.append({
                            "type": "redacted_thinking",
                            "data": data,
                        })

            save_message("assistant", assistant_blocks)
            conversation.append({"role": "assistant", "content": assistant_blocks})

            if response.stop_reason != "tool_use" or not tool_uses:
                break

            tool_result_blocks = []
            for tu in tool_uses:
                args = dict(tu.input) if tu.input else {}
                result = execute_tool(tu.name, args)
                ui_events.append({
                    "type": "tool_result",
                    "name": tu.name,
                    "preview": (result[:400] + "…") if len(result) > 400 else result,
                })
                tool_result_blocks.append({
                    "type": "tool_result",
                    "tool_use_id": tu.id,
                    "content": result,
                })

            save_message("user", tool_result_blocks)
            conversation.append({"role": "user", "content": tool_result_blocks})

        return ui_events

    def history(self) -> list[dict]:
        return load_history_for_ui(limit=80)

    def clear(self) -> None:
        clear_messages()
